= OS X Bundle Build Scripts

This is a collection of files required to build gPodder.app :
gPodder as a native GTK+ Quartz application for Mac OS X 10.6 and 10.7

The scripts are verified on an OSX 10.11.4 (15E65) `x86_64` machine with
Xcode 7.3 (7D175).

**Note:**
    In case you want just want to run gPodder from source you can ignore
    all this and use the released bundle as a development environment.
    Download the official bundle, git clone the gPodder repo and do
    `./gPodder.app/Contents/MacOS/run gpodder.py`.


Uses https://git.gnome.org/browse/jhbuild/[jhbuild] and the stable module
set provided by https://git.gnome.org/browse/gtk-osx/[gtk-osx] with a
gPodder specific module set overlay to build all needed dependencies for gPodder.
Everything will be downloaded/installed into this directory and your
user directory will not be touched.

Builds upon the great scripts by Christoph Reiter to automate my previously
tedious description.

== Creating a Bundle

Prerequisites: `OS X` 10.6+ and a working
https://developer.apple.com/xcode/downloads/[`Xcode`] and
https://git-scm.com/download/mac[`git`].

Verify that Xcode and git is installed and in your `$PATH` by invoking `git
--version` and `gcc --version`. The `env.sh` script resets your `$PATH` to the
default value (`{,/usr}/{,s}bin`) to make sure non-native programs, installed
by other package managers like homebrew or macports, are not used (read more
https://wiki.gnome.org/Projects/GTK+/OSX/Building#line-38[here]).

(Tested on OS X 10.11.4)

. Call `bootstrap.sh` to install jhbuild and set up dummy `$HOME` as base.
. Call `build.sh` to download and build all the dependencies.
. Call `bundle.sh` to create the finished bundles for gPodder in
   `_build`.


== Development

* After `bootstrap.sh` has finished executing `source env.sh` will put you
  in the build environment. After that jhbuild can be used directly.
* `fetch_modules()` downloads the git master of the gtk-osx module set
  and replaces the modules under "modulessets" and the
  `misc/gtk-osx-jhbuildrc` file. Doing so so should ideally be followed by a
  review of the gPodder module to reduce duplication and a rebuilt to verify
  that everything still works.


== Releasing

Releasing on OS X

. see *Creating a Bundle*
. `./release.sh _build/gPodder.app version_buildnumber`
. `./release_deps.sh _build/gPodder.app version_buildnumber`
 
Releasing on Linux by patching deps:

[start=4]
. `./release_on_linux.sh ~/Downloads/gPodder-3.8.4_0.deps.zip /tmp/gpodder master f699341`

== Issues

See https://github.com/elelay/gpodder-osx-bundle

== Using gPodder:

See https://github.com/elelay/gpoder-osx-bundle/wiki/Using for instructions...
And the official help guide http://gpodder.org/documentation



== Content Description

* `modulesets` contains the gtk-osx stable module set and a gpodder module
  which adds new packages replaces existing ones.
* `misc`: see each file or directory README for a description.
